name: mosaic
version: '2.7'
description: |
  This is NCSA Mosaic 2.7, one of the first graphical web browsers.
summary: NCSA Mosaic

confinement: strict
grade: stable

apps:
  mosaic:
    command: Mosaic
    plugs: [network,x11]

parts:
  mosaic:
    plugin: make
    build-packages: [libmotif-dev, libjpeg62-dev, libpng12-dev, x11proto-print-dev, libxmu-headers, libxpm-dev, libxmu-dev]
    source: https://github.com/alandipert/ncsa-mosaic
    source-type: git
    make-parameters: [linux]
    artifacts: [src/Mosaic]
    organize:
      src/Mosaic: .
